### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by jiejiangd** [haydengunraj/COVIDNet-CT#16]
As far as I know, the data set is from an article of Cell, but the number of slices described in the article is about 600,000, while the data you used is about 100,000. Why is that? And I don't think there are 600 million pieces of data available for download

**Comment by haydengunraj** [comment]
The discrepancy is due to two main factors. First, since we are doing per-slice detection (2D), we require slice-level ground-truth labels. Slice-level labels are provided in the Cell dataset, but only for a subset of patients. Second, many cases in the Cell dataset are segmented (i.e., the body surrounding the lungs is masked out), and so we had to exclude these cases as well. This leaves us with ~1800 patients, whereas the original dataset had ~3000.
