### ISSUE TITLE
CT labels

### ISSUE THREAD

**Issue by AlexTS1980** [haydengunraj/COVIDNet-CT#6]
I don't fully understand the labelling of the data. The paper says 'For NCP and CP CT volumes, slices marked as containing lung abnormalities were leveraged' - does it mean you only added scans that clearly display symptoms of (N)CP, leaving out slices without these symptoms?

**Comment by haydengunraj** [comment]
That's correct - in the [original CNCB dataset](http://ncov-ai.big.ac.cn/download?lang=en), they provide a file called `lesions_slices.csv` which lists CT slices for which radiologists have observed lung lesions due to CP/NCP. We use only the slices listed in this file when constructing the COVIDx-CT dataset, as we cannot guarantee that other slices from CP/NCP volumes contain abnormalities. For normal control cases, we use all slices.
